# version code 988
# Please fill out this stencil and submit using the provided submission script.

import random
from GF2 import one
from vec import Vec
from vecutil import list2vec
from independence import is_independent



## Problem 1
def randGF2(): return random.randint(0,1)*one
def flip(bit): return 0 if bit else one

a0 = list2vec([one, one,   0, one,   0, one])
b0 = list2vec([one, one,   0,   0,   0, one])

def choose_secret_vector(s,t):
    u = [randGF2() for i in range(6)]
    while not(a0 * list2vec(u) == s and b0 * list2vec(u) == t):
        i = random.randint(0, 5)
        u[i] = flip(u[i])
    return list2vec(u)



## Problem 2
# Give each vector as a Vec instance
# vecs are generated by running generate_bases.py
vecs = [Vec({0, 1, 2, 3, 4, 5},{0: one, 1: one, 2: 0, 3: one, 4: 0, 5: one}), Vec({0, 1, 2, 3, 4, 5},{0: one, 1: one, 2: 0, 3: 0, 4: 0, 5: one}), Vec({0, 1, 2, 3, 4, 5},{0: 0, 1: 0, 2: 0, 3: 0, 4: one, 5: one}), Vec({0, 1, 2, 3, 4, 5},{0: one, 1: one, 2: one, 3: 0, 4: one, 5: one}), Vec({0, 1, 2, 3, 4, 5},{0: one, 1: one, 2: 0, 3: 0, 4: one, 5: one}), Vec({0, 1, 2, 3, 4, 5},{0: 0, 1: one, 2: 0, 3: 0, 4: one, 5: one}), Vec({0, 1, 2, 3, 4, 5},{0: one, 1: one, 2: one, 3: 0, 4: 0, 5: one}), Vec({0, 1, 2, 3, 4, 5},{0: one, 1: 0, 2: 0, 3: one, 4: one, 5: one}), Vec({0, 1, 2, 3, 4, 5},{0: one, 1: 0, 2: 0, 3: 0, 4: 0, 5: one}), Vec({0, 1, 2, 3, 4, 5},{0: one, 1: 0, 2: one, 3: one, 4: one, 5: 0})]
secret_a0 = vecs[0]
secret_b0 = vecs[1]
secret_a1 = vecs[2]
secret_b1 = vecs[3]
secret_a2 = vecs[4]
secret_b2 = vecs[5]
secret_a3 = vecs[6]
secret_b3 = vecs[7]
secret_a4 = vecs[8]
secret_b4 = vecs[9]
